WebApp/Homework-04/Homework-04/Controllers/AdminController.cs
using Microsoft.Owin.Security;
using System;
using System.Web;
using System.Web.Mvc;

namespace Homework_04.Controllers
{
    public class AdminController : Controller
    {
        private IAuthenticationManager AuthenticationManager { get { return HttpContext.GetOwinContext().Authentication; } }

        public ActionResult Dashboard()
        {

            //if (User.IsInRole("Admin"))
            //{
                
            //}
            //Console.WriteLine(AuthenticationManager);
            ViewBag.Title = "Dashboard";
            return View("~/Views/Admin/Dashboard.cshtml");
            //return RedirectToAction("Index", "Home");

        }
    }
}

WebApp/Homework-04/Homework-04/Controllers/ResponseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Homework_04.Controllers
{
    public class ResponseController : Controller
    {
        // GET: Response
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApp/Homework-04/Homework-04/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace Homework_04.Controllers
{
    public class SurveyController : Controller
    {
        public ActionResult Manage()
        {
            ViewBag.Title = "Survey Manager";

            return View("~/Views/Survey/Manage.cshtml");
        }
    }
}

WebApp/Homework-04/Homework-04/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Homework_04.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            ViewBag.Title = "Message Manager";
            return View();
        }
    }
}

WebApp/Homework-04/Homework-04/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Care Me", "Dashboard", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("SignOut", "LogOff", "Home", new { area = "" }, null)</li>
                    }
                    
                    <!--<li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>-->
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Group5</p>
        </footer>
    </div>
    <script type="text/javascript">

        var yourApp = yourApp || {};
        yourApp.Urls = yourApp.Urls || {};
        yourApp.Urls.baseUrl = '@Url.Content("~")';
        yourApp.Urls.surveyManageUrl = '@Url.Action("Manage","Survey")';
        yourApp.Urls.responseManageUrl = '@Url.Action("Index","Response")';
        yourApp.Urls.homeScreenUrl = '@Url.Action("Index","Home")';
        yourApp.Urls.userMessagesUrl = '@Url.Action("Index","User")';

    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatable")
    @RenderSection("scripts", required: false)
</body>
</html>